default_title: Drunk On Rails
meta_keywords: "ruby on rails, ruby, tutorials, advanced, api, confident code, best practices"
meta_description: "Advanced Ruby on Rails articles on best-practices, confident code design, APIs, tips and tricks, and all kinds of awesome."
