default_title: David Lesches | Advanced Ruby on Rails
meta_keywords: "david lesches, ruby on rails, ror, ruby, tutorials, advanced, api, confident code, best practices"
meta_description: "Advanced Ruby on Rails articles from David Lesches on best-practices, confident code design, APIs, tips and tricks, and all kinds of awesome."
